name: Build

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git ref to checkout'
        required: false
        type: string
        default: ''
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Zip extensions
        run: |
          bun zip
          bun zip:firefox

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: .output/*.zip
          if-no-files-found: error
          include-hidden-files: true
          name: build