on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened


permissions:
  pull-requests: write

jobs:
  lint-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        name: Check Title
        id: check_title
        with:
          result-encoding: string
          script: |
            const pullRequestTitle = context.payload.pull_request.title;
            const pattern = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)?$/;

            if (pullRequestTitle.match(pattern)) {
              console.log("Title matches conventional commit. Good job");
              return "success"
            } else {
              var message = 'Pull request title does not match SemVer commit format';
              core.setFailed(message)
              return "failure"
            }
              
      - uses: marocchino/sticky-pull-request-comment@v2
        if: always() && (steps.lint_pr_title.outputs.result == 'failure')
        with:
          header: pr-title-lint-error
          message: |
            Hey there and thank you for opening this pull request! 👋🏼
            
            We require pull request titles to follow the [Semantic Versioning specification](https://semver.org/spec/v2.0.0.html) and it looks like your proposed title needs to be adjusted.

      # Delete a previous comment when the issue has been resolved
      - if: ${{ steps.lint_pr_title.outputs.error_message == 'success' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:   
          header: pr-title-lint-error
          delete: true