name: Publish Release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no actual release)'
        required: false
        default: true
        type: boolean

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: 
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PK }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: true

      - name: Build Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with: 
          git-push: ${{ github.event.inputs.dry_run == 'false' }}
          github-token: ${{ steps.app-token.outputs.token }}

      - name: Create Release
        if: ${{ github.event.inputs.dry_run == 'false' }}
        uses: softprops/action-gh-release@v2
        with:
          files: '*.zip'
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.changelog }}
